### ISSUE TITLE
Drum kit

### ISSUE THREAD

**Issue by BinilTomJose1278** [keshavgbpecdelhi/Web-Development#100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BinilTomJose1278** [comment]
This is basically a beginner friendly website done using HTML,CSS and Javascript  which produces different sounds of a drum when pressed on different keys displayed in the site, it improves and brushes the fundamentals of javascript

**Comment by keshavgbpecdelhi** [comment]
Closing wrt #102
