### ISSUE TITLE
[FEATURE] I want to add my project "Simon Game " to the README.md

### ISSUE THREAD

**Issue by Ayu1C** [keshavgbpecdelhi/Web-Development#115]
Hey @keshavgbpecdelhi !
I want to add my project "Simon Game" to the README.md
This is a game made using HTML, CSS, JavaScript and jQuery.
This game tests the memory of the player .
It highlights one button with background sound and asks the player to click the button followed by buttons from past levels.
The game ends when the player clicks on wrong button.

Please merge my pull request and add the label **"hacktoberfest"** to it.
![simon-game snap](https://user-images.githubusercontent.com/102305307/194234200-087f4f8b-2e51-4579-bb91-413d46052358.PNG)

**Comment by keshavgbpecdelhi** [comment]
closing wrt #117

**Comment by Ayu1C** [comment]
Thank you so much .😇
