### ISSUE TITLE
[FEATURE] I want to add my project "Maths4Kids"

### ISSUE THREAD

**Issue by Pranit-02** [keshavgbpecdelhi/Web-Development#129]
This project helps kids demonstrate and understand basic mathematical operation like add, sub, multi , div  easily using a webpage

The project is made by:
HTML ,CSS & JAVASCRIPT.

Plz consider this issue under Hacktoberfest'2022

**Comment by Pranav-Roy** [comment]
can you assign this to me, i can do some work on it.

**Comment by Pranit-02** [comment]
> can you assign this to me, i can do some work on it.

I created the issue bro, you can create other issue if you want to!!

**Comment by Pranit-02** [comment]
@keshavgbpecdelhi plz assign this issue to me

**Comment by keshavgbpecdelhi** [comment]
closing wrt #133
