### ISSUE TITLE
Let's Make README.md Catchy

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [keshavgbpecdelhi/Web-Development#15]
README.md getting long and boring, any innovative ideas !? I have some ideas we can do with it to look better and easily accessible.
We can make a Table like :
| About Page    | Live Page | Source Code     |
| :---        |    :----:   |          ---: |
| JS CALCULATOR    | [calculator](https://keshavgbpecdelhi.github.io/Web-Development/javascript/js-calculator/index.html)       | [index.html](https://github.com/keshavgbpecdelhi/Web-Development/blob/master/javascript/js-calculator/index.html)  |

Do the same with all other and arrange it properly make sure you don't mistake while placing the links, so be attentive while doing it. Else,

Any suggestions and more ideas are welcome alongside anyone can do the above suggested idea and PRs are welcome. Ask for assignment and start working just after asking, don't wait for the assignment tag, if I see it early I will assign it to you :))

**Comment by AayushBiswas** [comment]
I have already started making README.MD catch 
Here is the link : https://github.com/AayushBiswas/Web-Development
Is this how you want

**Comment by keshavgbpecdelhi** [comment]
> I have already started making README.MD catchy Here is the link : https://github.com/AayushBiswas/Web-Development Is this how you want
Absolutely @AayushBiswas you doing amazing. Yes go ahead like this. Assigning it to you 👍

**Comment by AayushBiswas** [comment]
Hi, I have made README.md catchy, I also gave a pull request can you accept it

**Comment by AayushBiswas** [comment]
> @AayushBiswas Are the links properly assigned, and redirecting well?

Yes

**Comment by keshavgbpecdelhi** [comment]
Awesome, merged successfully #18
