### ISSUE TITLE
Add random joke generator 

### ISSUE THREAD

**Issue by THE-AryanKumar** [keshavgbpecdelhi/Web-Development#154]
**Is your feature request related to a problem? Please describe.**
NO need

**Describe the solution you'd like**
No need

**Describe alternatives you've considered**
No need

**Additional context**
Add random joke generator webpage. Can you pls  /assign me.

**Comment by diva-21** [comment]
i have made and sent a pull req to you

**Comment by diva-21** [comment]
[Joke-Generator](https://github.com/keshavgbpecdelhi/Web-Development/pull/155/commits/d49a6767bc4cf34ea1b61f3d54fa1d13d2f358e9)

**Comment by THE-AryanKumar** [comment]
![2022-10-10 (3)](https://user-images.githubusercontent.com/97040203/194839518-97fa27c1-9cc6-4801-bee5-08e7ce35b452.png)

I have created a joke with great UI and features. Check it out.
I made the pr.
