### ISSUE TITLE
Adding a loading Screen Component

### ISSUE THREAD

**Issue by fosterer** [keshavgbpecdelhi/Web-Development#178]
**Is your feature request related to a problem? Please describe.**
I am adding a loading screen for a website.

**Describe the solution you'd like**
A preloader screen is a UI component that can be added to any website

**Describe alternatives you've considered**
An effective alternative is a splash screen.

**Additional context**
![Screenshot (553)](https://user-images.githubusercontent.com/109460028/195674818-47caef04-ac4c-4ad1-a630-07d9f04a4c9f.png)

**Comment by keshavgbpecdelhi** [comment]
Closing wrt #179
