### ISSUE TITLE
Contact Form 

### ISSUE THREAD

**Issue by m-mishra2001** [keshavgbpecdelhi/Web-Development#258]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by m-mishra2001** [comment]
can you please assign me this issue @keshavgbpecdelhi

**Comment by Deepanshu1008** [comment]
please assign me this issue

**Comment by pjyoti121** [comment]
Assign me this issue please 
and you just need a registration form right?

**Comment by keshavgbpecdelhi** [comment]
> Assign me this issue please and you just need a registration form right?

If you want, you can work on something else which is unique almost of the people are creating simple forms only. We already have 5 kind of forms here. @pjyoti121 you can create a new issue.
