### ISSUE TITLE
Quiz App 

### ISSUE THREAD

**Issue by 22tanyabansal** [keshavgbpecdelhi/Web-Development#266]
I want to add Quiz App made in HTML,CSS and JAVASCRIPT. Please assign this issue to me.

**Comment by Deepanshu1008** [comment]
please assign me this issue

**Comment by keshavgbpecdelhi** [comment]
Your work is merged @22tanyabansal #269.
You can check [here](https://github.com/keshavgbpecdelhi/Web-Development/tree/master/Quiz-app)
