### ISSUE TITLE
An Event Webpage

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [keshavgbpecdelhi/Web-Development#28]
You can make a static page holding an event. People who are interested in attending the conference create a register button for them. Mention different links for speaker, venue and schedule at the top in the header section. Describe the purpose of the conference or the category of people who can get benefit from this conference. Add an introduction and images of the speaker, venue detail and the main purpose of the conference on your webpage. Divide the page into sections, add header and footer showcasing the menu. Use proper background color that can go well with each other for various sections. Choose a descent font style and font color that matches the theme of your web page. It requires HTML/HTML5 and CSS knowledge in depth.

There is no limit in using various tech stacks just remember it would not going to mess up with our project 😅

Write `I am working on this` and start working.

**Comment by Manishgupta200** [comment]
I'm interested. Please assign
