### ISSUE TITLE
I want to add a website which helps in transforming the text written in it. 

### ISSUE THREAD

**Issue by dhruv1345** [keshavgbpecdelhi/Web-Development#307]
**Describe the solution you'd like**
My web app will be made using react js and it help in making changes to the text which needs to be transformed. Like operations like making it bold, uppercase or lowercase along with selecting whole text using one click.

**Comment by dhruv1345** [comment]
Assign me the task so that I can contribute by adding my project into the repo.

**Comment by dhruv1345** [comment]
[newapp-master.zip](https://github.com/keshavgbpecdelhi/Web-Development/files/10405293/newapp-master.zip)

This is a zip folder and I am attaching a link to preview it as well.

Link  : https://dhruv1345.github.io/newapp/

![1](https://user-images.githubusercontent.com/86596711/212161582-a2bef7e8-9f2f-4a7e-9423-ff8382c6d9c2.png)

**Comment by dhruv1345** [comment]
https://user-images.githubusercontent.com/86596711/212162565-1babee47-774a-406e-b45e-629fd7c49960.mp4

**Comment by dhruv1345** [comment]
Done with my part.

Do let me know if it is merged.

**Comment by keshavgbpecdelhi** [comment]
Please do a PR by making a new directory so that it can be merged. Your PR should be present [here](https://github.com/keshavgbpecdelhi/Web-Development/pulls).

**Comment by dhruv1345** [comment]
I have made the changes. Please check.
