### ISSUE TITLE
[FEATURE] Guess the Number Game

### ISSUE THREAD

**Issue by shantanunautiyal** [keshavgbpecdelhi/Web-Development#328]
![game](https://github.com/keshavgbpecdelhi/Web-Development/assets/56751285/7e70a6b3-ea1e-43d7-a5c7-dba9d9a48819)

**Comment by keshavgbpecdelhi** [comment]
Nice one, go ahead @shantanunautiyal remember to edit it in README.md as well

**Comment by shantanunautiyal** [comment]
@keshavgbpecdelhi Please check the pull request
