### ISSUE TITLE
Photography web page

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [keshavgbpecdelhi/Web-Development#33]
The idea is to create a one-page responsive photography site. 
You can create a gallery with a view button so users can go to the images section and slide to view the following images. You can keep different viewing layouts like a grid, list, etc. Add the margin and padding for the page and choose your desired color combination, font style, and image size. For responsiveness quotient, you can use flexbox and media queries.
Update README accordingly. 
Tag the issue while  sending a PR.

**Comment by Manishgupta200** [comment]
Hay, I would like to work on it. Please assign it to me
