### ISSUE TITLE
[FEATURE] Add Simple Login/Sign up page

### ISSUE THREAD

**Issue by AbhayDonga007** [keshavgbpecdelhi/Web-Development#347]
Add login/sign up page

**Comment by keshavgbpecdelhi** [comment]
Similar to this is already done many times in this repository, it would be better if you can enhance previously done work of others.

**Comment by AparajitaSingh121416** [comment]
hey @AbhayDonga007 please assign this issue to me.

**Comment by Prabhsingh0401** [comment]
Hey I have made an amazing login and signup page can you assign me this issue .
Thank You

**Comment by Albert-2** [comment]
hey can you please assign me this issue 
THANK YOU...!!:)

**Comment by SakshiJSanghavi** [comment]
Hey, can you please assign me this issue?

**Comment by AbhayDonga007** [comment]
> hey @AbhayDonga007 please assign this issue to me.

Ok, keep working on it.

**Comment by sumant5214** [comment]
hey @AbhayDonga007 can you assign this issue to me
