### ISSUE TITLE
Added Pure HTML CSS Restaurant website

### ISSUE THREAD

**Issue by HarshwardhanPatil07** [keshavgbpecdelhi/Web-Development#354]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the current restaurant website uses complex frameworks and libraries, making it difficult to maintain and load slowly.

**Describe the solution you'd like**
In this case, I would like a pure HTML and CSS-based restaurant website to be added, which would simplify the website's structure and improve its performance.

**Describe alternatives you've considered**
One alternative could be to continue using a complex framework, but it may not be the most efficient and user-friendly option for a restaurant website.

#hactoberfest
@keshavgbpecdelhi

**Comment by akash0708** [comment]
Hello @HarshwardhanPatil07 , can I work on this under hacktoberfest 2023? @keshavgbpecdelhi
