### ISSUE TITLE
Make Basic 2D/3D shapes using CSS

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [keshavgbpecdelhi/Web-Development#46]
Note : Try to make as simple as possible. It's ok not to draw 3D shapes or complex shapes. It's up to you.

# HOW THE PAGE SHOULD LOOK LIKE ?
![shapes.html](https://user-images.githubusercontent.com/56075233/139629326-fcb529ef-a176-4052-85dc-f69b4258be4e.jpg)

**Comment by TamHoChi3008** [comment]
Hi, can I try to help this issue?

**Comment by keshavgbpecdelhi** [comment]
Ya, sure 👍

**Comment by keshavgbpecdelhi** [comment]
It is looking really good , just can you arrange the shapes in an order so that they look decent. It can be vertically or horizontally or just like the above drawing I made. 

@TamHoChi3008 here is the current view of the page - https://keshavgbpecdelhi.github.io/Web-Development/SHAPES/

**Comment by keshavgbpecdelhi** [comment]
![SHAPES](https://user-images.githubusercontent.com/56075233/140535611-c99051e2-6703-44c3-8b5b-a856840702a7.jpg)

**Comment by TamHoChi3008** [comment]
ok !!

**Comment by keshavgbpecdelhi** [comment]
Thanks again 👏
