### ISSUE TITLE
2D_Tranforms

### ISSUE THREAD

**Issue by Gnupur** [keshavgbpecdelhi/Web-Development#49]
Hello, This is really a well mannered beginner friendly project ! I loved it ! I would like to add features related to 2D transformations in CSS.

**Comment by keshavgbpecdelhi** [comment]
Sure @Gnupur go ahead make a PR, also don't forget to add your contribution link in README.MD table.

**Comment by Gnupur** [comment]
Thanks for your response! Just a tiny doubt , to add the link to the folder
in README.MD the pull request should get accepted and then only I can have
a link to add right ?
Have a nice day :)

**Comment by keshavgbpecdelhi** [comment]
No that's not necessary, you can upload files and update README.MD at once then you can send PR, will merge after reviewing.

**Comment by Gnupur** [comment]
Okay I have made a pull request but uploading files need a push access it
is saying so I have created new file.

**Comment by keshavgbpecdelhi** [comment]
wrt #50 :
That's awesome contribution, hope you will add more transformations in future

**Comment by keshavgbpecdelhi** [comment]
closing via #50
