### ISSUE TITLE
[FEATURE] I want to work on CSS Cursor Viewer

### ISSUE THREAD

**Issue by RahulSahOfficial** [keshavgbpecdelhi/Web-Development#59]
**Is your feature request related to a problem? Please describe.**
While developing webpages we often get confuse while using CSS cursor

**Describe the solution you'd like**
I want to make a webpage under CSS Directory in which user can view different type of cursor by hovering on it and get
proper idea of which cursor style to use when and get the code easily.

Here is the inspiration link : https://www.cssportal.com/css-cursor-viewer/ 
and Demo image
![image](https://user-images.githubusercontent.com/62435110/193421189-33843940-6056-4a77-b5db-862265f86d2a.png)

Assign me on this task so I start working on it...
@keshavgbpecdelhi

**Comment by keshavgbpecdelhi** [comment]
Ofcourse! Go ahead just make sure the directory path you put this project in must in right place.
