### ISSUE TITLE
[FEATURE] Gradient-Generator

### ISSUE THREAD

**Issue by harshit-maheshwari** [keshavgbpecdelhi/Web-Development#60]
**Is your feature request related to a problem? Please describe.**
As a front-end developer picking up colors and gradient is always a huge problem, we are unable to decide which gradient will look best for our website. 
There must be a gradient generator which a programmer can use and copy the gradient code directly to its website

**Describe the solution you'd like**
I want to add a gradient-generator based on simple _HTML5, CSS3 & Javascript,_ which can help a programmer to select colors using color inputs and will be able to directly copy the code for the gradient

**Describe alternatives you've considered**
These are a lot of alternatives but most of them are cumbersome and programmer finds it difficult to choose between already provided color pallettes, also this makes the whole process less innovative as programmer will be using an already created generic color pallette, here my code will help programmer to choose pallette according to the demand of either business or the programmer itself.

**Additional context**
![image](https://user-images.githubusercontent.com/55666814/193421725-ec17d2ad-6d5a-409e-8939-7b614b631acb.png)

**Comment by harshit-maheshwari** [comment]
Please allow me to work for this enhancement

**Comment by keshavgbpecdelhi** [comment]
Ofcourse! Go ahead just make sure the directory path you put this project in must in right place.

**Comment by keshavgbpecdelhi** [comment]
Awesome work @harshit-maheshwari. Thanks for your valuable contribution. 

Closing wrt #62
