### ISSUE TITLE
Enhance Animated Search Form

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [keshavgbpecdelhi/Web-Development#65]
Do you know how to play with CSS?
Do you have little bit of Animations skills?
What do think "an ideal Animated Search Form" looks like?

Having answers to these questions or getting excited with your thoughts, let's improve our search form (coz literally no work done on it till now) and make it better !

Share your ideas and then go for PR!

Check folder : [Animated Search Form](https://github.com/keshavgbpecdelhi/Web-Development/tree/master/Animated%20Search%20Form)

**Comment by prjailani** [comment]
Hi, can you please assign this to me?

**Comment by satyamrs00** [comment]
My idea:
initially the search bar will be circular , and when you click on it then it restores to its full size 
initially it will have a faint search icon which will go to far right when expanded and act as submit button.

Now, Can you assign this to me ?

**Comment by cenacrharsh** [comment]
I am thinking of starting off as a search icon and when pressed it will expand and display some text, then expanding will be animated and text can also autotype itself. Please assign it to me @keshavgbpecdelhi.

**Comment by keshavgbpecdelhi** [comment]
I like the idea of autotyping @cenacrharsh assigning it to you. Hope you will do it asap, else I need to asign it to @satyamrs00 !

Meanwhile, @satyamrs00 & @prjailani there are more projects which are needed to be enhanced, and you can even submit a new project as well just make an issue. 

Happy coding!

**Comment by keshavgbpecdelhi** [comment]
Closing wrt #73
