### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by vishakha868** [keshavgbpecdelhi/Web-Development#67]
**Is your feature request related to a problem? Please describe.**
Most of the websites use a carousel which is needed by beginners to learn.

**Describe the solution you'd like**
I wanted to add a webpage in the bootstrap directory so that beginners can easily learn to create one.

**Comment by keshavgbpecdelhi** [comment]
Go ahead @vishakha868 !

**Comment by keshavgbpecdelhi** [comment]
closing wrt #70
