### ISSUE TITLE
[FEATURE] A Hybrid CSS and JS based animated webpage

### ISSUE THREAD

**Issue by heza-ru** [keshavgbpecdelhi/Web-Development#68]
**Is your feature request related to a problem? Please describe.**
This repo lacks some custom animations based on simple front end stack.

**Describe the solution you'd like**
I want to add a custom CSS and JS based hybrid animation based on mouse hover over html elements.

**Comment by keshavgbpecdelhi** [comment]
Even tho this repo has some mouse hover animations just make sure to create with a new idea. Assigning it to you @heza-ru

**Comment by keshavgbpecdelhi** [comment]
Closing wrt #71
