### ISSUE TITLE
A Responsive Portfolio Website using HTML, CSS and bit of JavaScript

### ISSUE THREAD

**Issue by bugsyy157** [keshavgbpecdelhi/Web-Development#72]

**Comment by bugsyy157** [comment]
please assign me this.Would love to work on this

**Comment by keshavgbpecdelhi** [comment]
It's already being made if you can enhance it then go ahead @bugsyy157 

Portfolio : (Code)[https://github.com/keshavgbpecdelhi/Web-Development/tree/master/css-7]

**Comment by bugsyy157** [comment]
Sure :)
