### ISSUE TITLE
[FEATURE] I want to work on CSS Animation Timing Function

### ISSUE THREAD

**Issue by RahulSahOfficial** [keshavgbpecdelhi/Web-Development#76]
Is your feature request related to a problem? Please describe.
While developing webpages we often get confuse while using different CSS Animation Timing Function

Describe the solution you'd like
I want to make a webpage in which user can view different type of CSS Animation Timing Function at a time and how the complete animation proceeds so user can have proper idea of which animation timing function to use when and get the code easily.

Different CSS Animation Timing Function
1. linear
2. ease
3. ease-in
4. ease-out
5. ease-in-out

Here is the inspiration link : https://www.w3schools.com/cssref/playit.asp?filename=playcss_animation-timing-function&preval=ease-in-out
and Demo Inspiration image
![image](https://user-images.githubusercontent.com/62435110/193464069-4189295b-2c4a-4bd1-aeaf-38d58fb1b7ae.png)

Assign me on this task so I start working on it...
@keshavgbpecdelhi

**Comment by keshavgbpecdelhi** [comment]
Go ahead @RahulSahOfficial
