### ISSUE TITLE
[BUG] There are 2 bugs in Contributing.md

### ISSUE THREAD

**Issue by aakashgarg-19** [keshavgbpecdelhi/Web-Development#78]
**Describe the bug**
1.  Step of  "cd [name of folder] " is missing before step 4 of adding upstream
2.  Instead "git pull upstream main" --> "git pull upstream master" in step 5

**Comment by aakashgarg-19** [comment]
Please assign me this issue

**Comment by aakashgarg-19** [comment]
@keshavgbpecdelhi  Please assign me this issue

**Comment by aakashgarg-19** [comment]
Done

**Comment by keshavgbpecdelhi** [comment]
Closing wrt #104
