### ISSUE TITLE
Build A Simple Java Script Calculator

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [keshavgbpecdelhi/Web-Development#8]
Example : https://codepen.io/sujanchhetri/full/BaBRQqv
Don't worry about making things complex a simple demo page would be fine. No need to be exact, that was just an example.

Remember to update README.md the way it's been so far (add live page link also).

**Comment by NaimaGhulamMuhammad** [comment]
can you assign this to me...?

**Comment by SHAMUNESH** [comment]
Hey there! I would like to contribute in this : ) Pls assign

**Comment by keshavgbpecdelhi** [comment]
@NaimaGhulamMuhammad Amazing work 🎉
