### ISSUE TITLE
[FEATURE] Sticky Nav and Sticky footer

### ISSUE THREAD

**Issue by Sanjanabharadwaj25** [keshavgbpecdelhi/Web-Development#82]
**Is your feature request related to a problem? Please describe.**
All websites contain a sticky nav bar and footers. It would be useful for anyone learning how to go about it.

**Describe the solution you'd like**
A simple navigation bar and footer that shows how to fix an element.

**Comment by keshavgbpecdelhi** [comment]
Go Ahead @Sanjanabharadwaj25 ! Just make sure to let this be in an appropriate directory or make a new one.
