### ISSUE TITLE
[FEATURE] A resume builder

### ISSUE THREAD

**Issue by stuck-in-a-conundrum** [keshavgbpecdelhi/Web-Development#89]
**Is your feature request related to a problem? Please describe.**
A way to present resume details in a formatted manner

**Describe the solution you'd like**
A static webpage to enter details, and have the presented in a resume format

**Additional context**
Providing multiple themes for the user to choose from!

**Comment by keshavgbpecdelhi** [comment]
Go for it @stuck-in-a-conundrum create a new directory & make sure to add it in README.md table

**Comment by keshavgbpecdelhi** [comment]
Closing wrt #94
