### ISSUE TITLE
Build A Demo Tribute Page And Update README.md with live page link 

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [keshavgbpecdelhi/Web-Development#9]

**Comment by aarrpitt** [comment]
Hello Sir, can I work on this?

**Comment by aarrpitt** [comment]
Yes, Sir, I will complete it by today.

**Comment by aarrpitt** [comment]
@keshavgbpecdelhi   Hi! I have completed the task ,please review my PR #29 and suggest some changes if necessary and please merge it.
Thank You!
