### ISSUE TITLE
[FEATURE] Dark mode

### ISSUE THREAD

**Issue by Bhavya-C-ai** [keshavgbpecdelhi/Web-Development#90]
I would like to add a toggle button to switch the home page from light to dark mode.

I would like to use vanilla js and css for it.

Something like this.
![image](https://user-images.githubusercontent.com/96719986/193711594-2766d982-890d-4e0e-8222-3c75ee788461.png)
Can this issue be assigned to me under the hacktober label?

**Comment by keshavgbpecdelhi** [comment]
Go ahead @Bhavya-C-ai 👍

**Comment by Bhavya-C-ai** [comment]
It's done. You can check it in open PRs. Check it out and let me know any feedback :)

**Comment by keshavgbpecdelhi** [comment]
Great work @Bhavya-C-ai
