### ISSUE TITLE
[FEATURE] Update the UI of Event

### ISSUE THREAD

**Issue by mohammadshaad** [keshavgbpecdelhi/Web-Development#95]
I want to update the Event UI. Actually, its UI needed to be changed e.g., font size, line-heights of the paragraphs, buttons, etc. 

Font has to be changed to something more readable or terminal font like IBM Plex Mono and font size has to be decreased a little. I will increase the height and width of the buttons and centre the button on the page. I will change the icons and the line height of the paragraphs. Also, I will change the html code a little bit.

**Comment by keshavgbpecdelhi** [comment]
Go ahead @mohammadshaad !
