### ISSUE TITLE
Roll-the-Dice

### ISSUE THREAD

**Issue by Khushi260** [keshavgbpecdelhi/Web-Development#96]
This is basically a 2 player dice game created using HTML, CSS and Javascript.

In this game, everytime user hit refresh button both dices throws new numbers.
Depending on these numbers on the die winners get decided.

This is my first issue in opensource contribution
Consider this as contribution under hacktoberfest 2022.

**Comment by keshavgbpecdelhi** [comment]
Closing wrt #101
